version: '3'
services:
  orpington-news:
    container_name: orpington-news-e2e
    image: orpington-news-e2e:latest
    environment:
      - APP_URL=http://localhost:8000
      - DB_HOST=db
      - DB_PASS=dbpass
      - DISABLE_SECURE_COOKIE=true
    ports:
      - '8000:8000'
    networks:
      - orpington-news
    restart: always

  db:
    image: postgres:14-alpine
    container_name: orpington-news-e2e-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
    networks:
      - orpington-news
    ports:
      - '8001:5432'
    restart: always

  feeds:
    container_name: orpington-news-e2e-feeds
    build:
      context: .
      dockerfile: docker/Dockerfile.e2e.feeds
    ports:
      - '8002:8002'
    volumes:
      - ./cypress/feeds:/public:ro
    networks:
      - orpington-news
    restart: always

networks:
  orpington-news:
