version: '3'
services:
  orpington-news-api:
    image: ghcr.io/frysztak/orpington-news-api:latest
    container_name: orpington-news
    environment:
      - APP_URL=https://news.${DOMAINNAME}
      - DB_HOST=orpington-news-postgres
      - DB_PASS=dbpass
      - TZ=${TIMEZONE}
      - COOKIE_SECRET="9WdSXIL+/9B6DlMsh3BwCMX6nf2S2zN3dSwD6O4A66A="
    networks:
      - orpington-news
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.orpington-news-api-rtr.rule=Host(`news.${DOMAINNAME}`)'
      - 'traefik.http.routers.orpington-news-api-rtr.tls=true'
      - 'traefik.http.routers.orpington-news-api-rtr.entrypoints=https'
      - 'traefik.http.routers.orpington-news-api-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.orpington-news-api-rtr.service=orpington-news-api-svc'
      - 'traefik.http.services.orpington-news-api-svc.loadbalancer.server.scheme=http'
      - 'traefik.http.services.orpington-news-api-svc.loadbalancer.server.port=8000'

  orpington-news-postgres:
    image: postgres:14-alpine
    container_name: orpington-news-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - ${DOCKER_LOCAL_DIR}/orpington-news/postgres/data:/var/lib/postgresql/data
    networks:
      - orpington-news
    restart: always

networks:
  orpington-news:
