name: 'Unit tests'
description: 'Runs unit tests using Jest'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: Install deps
      shell: bash
      run: |
        yarn install --immutable
      env:
        CYPRESS_INSTALL_BINARY: '0'

    - name: Build shared package
      shell: bash
      run: |
        yarn workspace @orpington-news/shared run build

    - name: Run unit tests
      shell: bash
      run: |
        yarn test
