import React from 'react';
import { BsCodeSlash, BsCodeSquare, BsTerminal } from 'react-icons/bs';
import { DiAndroid, DiFsharp, DiGo } from 'react-icons/di';
import { ImDatabase, ImHackernews } from 'react-icons/im';
import {
  SiAngular,
  SiApple,
  SiArchlinux,
  SiClojure,
  SiDebian,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiErlang,
  SiFirefox,
  SiGit,
  SiGithub,
  SiGnu,
  SiGooglechrome,
  SiHaskell,
  SiHtml5,
  SiJava,
  SiJavascript,
  SiLinux,
  SiMarkdown,
  SiMozilla,
  SiNeovim,
  SiNextdotjs,
  SiNpm,
  SiPhp,
  SiPython,
  SiRaspberrypi,
  SiReact,
  SiRedux,
  SiRust,
  SiStackoverflow,
  SiSwift,
  SiTypescript,
  SiUbuntu,
  SiWordpress,
} from 'react-icons/si';
import { CollectionIconType } from '@orpington-news/shared/dist/types';

export interface CollectionIconProps {
  icon?: CollectionIconType;
}

const icons: Record<CollectionIconType, React.FC> = {
  Android: DiAndroid,
  Angular: SiAngular,
  Apple: SiApple,
  Archlinux: SiArchlinux,
  Chrome: SiGooglechrome,
  Clojure: SiClojure,
  Code: BsCodeSlash,
  CodeBadge: BsCodeSquare,
  Database: ImDatabase,
  Debian: SiDebian,
  Deno: SiDeno,
  Django: SiDjango,
  Docker: SiDocker,
  Dotnet: SiDotnet,
  Erlang: SiErlang,
  Firefox: SiFirefox,
  Fsharp: DiFsharp,
  Git: SiGit,
  Github: SiGithub,
  GNU: SiGnu,
  Golang: DiGo,
  HackerNews: ImHackernews,
  Haskell: SiHaskell,
  HTML: SiHtml5,
  Java: SiJava,
  JavaScript: SiJavascript,
  Linux: SiLinux,
  Markdown: SiMarkdown,
  Mozilla: SiMozilla,
  NextJS: SiNextdotjs,
  NPM: SiNpm,
  PHP: SiPhp,
  Python: SiPython,
  RaspberryPI: SiRaspberrypi,
  React: SiReact,
  Redux: SiRedux,
  Rust: SiRust,
  StackOverflow: SiStackoverflow,
  Swift: SiSwift,
  Terminal: BsTerminal,
  TypeScript: SiTypescript,
  Ubuntu: SiUbuntu,
  Vim: SiNeovim,
  Wordpress: SiWordpress,
};

export const getCollectionIcon = (iconType?: CollectionIconType): React.FC => {
  return icons[iconType ?? 'Code'];
};
