import React from 'react';
import { BsCodeSlash, BsCodeSquare, BsTerminal } from 'react-icons/bs';
import { DiAndroid, DiFsharp, DiGo } from 'react-icons/di';
import { ImDatabase, ImHackernews } from 'react-icons/im';
import {
  SiAngular,
  SiApple,
  SiArchlinux,
  SiClojure,
  SiDebian,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiErlang,
  SiFirefox,
  SiGit,
  SiGithub,
  SiGnu,
  SiGooglechrome,
  SiHaskell,
  SiHtml5,
  SiJava,
  SiJavascript,
  SiLinux,
  SiMarkdown,
  SiMozilla,
  SiNeovim,
  SiNextdotjs,
  SiNpm,
  SiPhp,
  SiPython,
  SiRaspberrypi,
  SiReact,
  SiRedux,
  SiRust,
  SiStackoverflow,
  SiSwift,
  SiTypescript,
  SiUbuntu,
  SiWordpress,
} from 'react-icons/si';

export const FeedIcons = [
  'Android',
  'Angular',
  'Apple',
  'Archlinux',
  'Chrome',
  'Clojure',
  'Code',
  'CodeBadge',
  'Database',
  'Debian',
  'Deno',
  'Django',
  'Docker',
  'Dotnet',
  'Erlang',
  'Firefox',
  'Fsharp',
  'Git',
  'Github',
  'GNU',
  'Golang',
  'HackerNews',
  'Haskell',
  'HTML',
  'Java',
  'JavaScript',
  'Linux',
  'Markdown',
  'Mozilla',
  'NextJS',
  'NPM',
  'PHP',
  'Python',
  'RaspberryPI',
  'React',
  'Redux',
  'Rust',
  'StackOverflow',
  'Swift',
  'Terminal',
  'TypeScript',
  'Ubuntu',
  'Vim',
  'Wordpress',
] as const;

export type FeedIconType = typeof FeedIcons[number];

export interface FeedIconProps {
  icon?: FeedIconType;
}

const icons: Record<FeedIconType, React.FC> = {
  Android: DiAndroid,
  Angular: SiAngular,
  Apple: SiApple,
  Archlinux: SiArchlinux,
  Chrome: SiGooglechrome,
  Clojure: SiClojure,
  Code: BsCodeSlash,
  CodeBadge: BsCodeSquare,
  Database: ImDatabase,
  Debian: SiDebian,
  Deno: SiDeno,
  Django: SiDjango,
  Docker: SiDocker,
  Dotnet: SiDotnet,
  Erlang: SiErlang,
  Firefox: SiFirefox,
  Fsharp: DiFsharp,
  Git: SiGit,
  Github: SiGithub,
  GNU: SiGnu,
  Golang: DiGo,
  HackerNews: ImHackernews,
  Haskell: SiHaskell,
  HTML: SiHtml5,
  Java: SiJava,
  JavaScript: SiJavascript,
  Linux: SiLinux,
  Markdown: SiMarkdown,
  Mozilla: SiMozilla,
  NextJS: SiNextdotjs,
  NPM: SiNpm,
  PHP: SiPhp,
  Python: SiPython,
  RaspberryPI: SiRaspberrypi,
  React: SiReact,
  Redux: SiRedux,
  Rust: SiRust,
  StackOverflow: SiStackoverflow,
  Swift: SiSwift,
  Terminal: BsTerminal,
  TypeScript: SiTypescript,
  Ubuntu: SiUbuntu,
  Vim: SiNeovim,
  Wordpress: SiWordpress,
};

export const getFeedIcon = (iconType?: FeedIconType): React.FC => {
  return icons[iconType ?? 'Code'];
};
