name: CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: ./.github/actions/unit

  e2e:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
      - uses: ./.github/actions/e2e
        with:
          cypress-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
