name: Deploy dev

on:
  push:
    branches:
      - dev
      - feat/ci
    paths:
      - '.github/workflows/dev.yml'
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push API to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@orpington.software:22/news-dev-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Push app to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@orpington.software:22/news-dev-app'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}