name: CD Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build API
        uses: docker/build-push-action@v2
        with:
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          load: true
          tags: frysztak/orpington-news-api:latest
      - name: Build APP
        uses: docker/build-push-action@v2
        with:
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          load: true
          tags: frysztak/orpington-news-app:latest

      - name: Push API
        uses: docker/build-push-action@v2
        with:
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          push: true
          tags: frysztak/orpington-news-api:latest
      - name: Push APP
        uses: docker/build-push-action@v2
        with:
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          push: true
          tags: frysztak/orpington-news-app:latest
