name: CD MAIN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build API
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: packages/backend
          load: true
          tags: frysztak/orpington-news-api:latest
      - name: Build APP
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: packages/frontend
          load: true
          tags: frysztak/orpington-news-app:latest
      - name: Push API
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: packages/backend
          push: true
          tags: frysztak/orpington-news-api:latest
      - name: Push APP
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: packages/frontend
          push: true
          tags: frysztak/orpington-news-app:latest
